import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import ConvexClientProvider from "@/components/ConvexClientProvider";
import GlobalNotifications from "@/components/global-notifications";
// import TopNav from "@/components/top-nav";
import { ToastProvider } from "@/components/ui/toast-provider";
// import { WebPushInit } from "@/components/web-push-init";
import { Toaster } from "@/components/ui/sonner"


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/Cyberlooplogo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}  antialiased`}
      >
        {/* <WebPushInit /> */}
        <Toaster richColors />
        <ToastProvider>
          <ConvexClientProvider>
           
            {children}
          </ConvexClientProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
