import type { Metadata } from "next";
import "@/app/globals.css";
// import TopNav from "@/components/top-nav";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Separator } from "@/components/ui/separator";
import BreadcrumbDynamic from "@/components/breadcrumb-dynamic";
import { CreateTicketModal } from "@/components/create-ticket-modal";
import { SiteHeader } from "@/components/site-header";
import { AppSidebarNew } from "@/components/app-sidebar-new";
import GlobalNotifications from "@/components/global-notifications";
// import { WebPushInit } from "@/components/web-push-init";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider defaultOpen={false}>
      <AppSidebarNew  />
      <SidebarInset>
        {/* <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12 border-b ">
          <div className="flex items-center gap-2 px-4">
            <SidebarTrigger className="-ml-1" />
            <Separator
              orientation="vertical"
              className="mr-2 data-[orientation=vertical]:h-4"
            />
            <div className="flex flex-1 items-center justify-between gap-4 min-w-0">
              <BreadcrumbDynamic />
              <div className="flex items-center gap-2">
                <CreateTicketModal />
              </div>
            </div>
          </div>
        </header> */}
        <div className="flex flex-1 flex-col">
          <div className="@container/main flex flex-1 flex-col gap-2 bg-muted/30">
            {children}
          </div>
        </div>
         <GlobalNotifications />
      </SidebarInset>
    </SidebarProvider>
  );
}
