import type { Metadata } from "next";
import "@/app/globals.css";
// import TopNav from "@/components/top-nav";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Separator } from "@/components/ui/separator";
import BreadcrumbDynamic from "@/components/breadcrumb-dynamic";
import { CreateTicketModal } from "@/components/create-ticket-modal";
// import { WebPushInit } from "@/components/web-push-init";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

            <SidebarProvider
              style={
                {
                  "--sidebar-width": "350px",
                } as React.CSSProperties
              }
            >
              <AppSidebar />
              <SidebarInset>
                <header className="bg-background sticky top-0 flex shrink-0 items-center gap-2 border-b p-4">
                  <SidebarTrigger className="-ml-1" />
                  <Separator
                    orientation="vertical"
                    className="mr-2 data-[orientation=vertical]:h-4"
                  />
                  <div className="flex flex-1 items-center justify-between gap-4 min-w-0">
                    <BreadcrumbDynamic />
                    <div className="flex items-center gap-2"><CreateTicketModal /></div>
                  </div>
                </header>
                <div className="w-full">
                  {children}

                </div>
              </SidebarInset>
            </SidebarProvider>

  );
}
